# Generated by Django 4.2.5 on 2024-01-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resume_title1_alter_resume_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='Website',
            new_name='website',
        ),
    ]
